language: node_js
node_js:
  - "node"
before_install: cd server/
install:
  - npm install
  - npm install -g mocha
  - npm install -g chai
  - npm install -g chai-http
  - npm install eslint -g
  - npm install eslint-plugin-react -g
script:
  - npm test
